apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline4-app
  namespace: abc-bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipeline4-app
  template:
    metadata:
      labels:
        app: pipeline4-app
    spec:

      # ðŸ”¹ INIT CONTAINER (YEH MISSING THA)
      initContainers:
      - name: copy-html
        image: sshivaji555/pipeline4-app:latest
        command:
          - sh
          - -c
          - cp /usr/share/nginx/html/index.html /pv/index.html
        volumeMounts:
        - name: html-volume
          mountPath: /pv

      # ðŸ”¹ MAIN CONTAINER
      containers:
      - name: nginx
        image: sshivaji555/pipeline4-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html

      # ðŸ”¹ VOLUME (PVC)
      volumes:
      - name: html-volume
        persistentVolumeClaim:
          claimName: pipeline4-pvc
