apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline4-app
  namespace: abc-bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipeline4
  template:
    metadata:
      labels:
        app: pipeline4
    spec:
      containers:
      - name: nginx
        image: nginx:1.29.4-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        persistentVolumeClaim:
          claimName: pipeline4-pvc
