apiVersion: v1
kind: Service
metadata:
  name: pipeline4-service
spec:
  type: NodePort
  selector:
    app: pipeline4-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30086  # <-- change this to an unused port
