apiVersion: v1
kind: Service
metadata:
  name: pipeline3-service
spec:
  type: NodePort
  selector:
    app: pipeline3-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30085  # <-- change this to an unused port
